name: Composite Action Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v4

      - name: Run Setup and Greet Action
        id: greet
        uses: ./.github/actions/setup-and-greet
        with:
          name: "Akash"
          language: "es"

      - name: Print the Action Output
        run: |
          echo "Greeting Completed: ${{ steps.greet.outputs.greeted }}"