name: this is a manual trigger workflow ask user for environment value
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Please select the environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  manual-triger-jon:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print message
        run: echo "This is a manual trigger workflow"

      - name: print selected environment
        run: | 
          echo  "Selected environment: ${{ github.event.inputs.environment }}"