name: PR validation
on:
  pull_request:
    branches:
      - main
  
jobs:
  file-size-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v7
      - name: check file size
        run: |
          echo "Checking for file larger then 1 MB..."
          large_file=$(find . -type f -size +1M -not -path "./.git/*")

          if [ -n "$large_file" ]; then
            echo "::error::Files larger than 1 MB found:"
            echo "$large_files"
            exit 1
          fi

          echo "All files are within the 1 MB limit."

  branch-name-check:
    runs-on: ubuntu-latest
    steps:
      - name: Reads the branch name
        run: echo "Source branch = ${{ github.head_ref }}"

      - name: Validate branch name
        run: |
                branch="${{ github.head_ref }}"

                if [[ "$branch" == feature/* || "$branch" == fix/* || "$branch" == docs/* ]]; then
                  echo "Valid branch name: $branch"
                else
                  echo "::error::Invalid branch name: $branch"
                  echo "Use feature/*, fix/*, or docs/*"
                  exit 1
                fi

  pr-body-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Description
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          if [[ -z "${PR_BODY//[[:space:]]/}" ]]; then
                  echo "::warning::PR description is empty."
                else
                  echo "PR description is present."
                fi