name: Run Shell Tests in CI

on:
  push:
    paths:
      - "scripts/test-add.sh"
      - ".github/workflows/run-tests.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Shell tests
        run: bash scripts/test-add.sh