name: MY_SECRET_MESSAGE-demo

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret Exist
        run: |
          if [ -n "${{secrets.MY_SECRET_MESSAGE}}" ]; then
            echo "The secret is set: true"
          else
            echo "the secret is missing..."
          fi
      
      - name: print the secret message
        run: |
          echo "The secret is ${{secrets.MY_SECRET_MESSAGE}}"

