name: Secrets with env practice

on: 
  workflow_dispatch:

jobs:
  docker-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        run: |
          echo "Docker username is ${{secrets.DOCKER_USERNAME}}"
          echo "Login into Docker Completed!!"